# This file is a reference scaffold — it has been moved to the working location.
#
# Your implementation of build_graph() should go in:
#
#   agent/graph.py  (stub with NotImplementedError is already there)
#
# Do not edit this file.