# This file is a reference scaffold — it has been moved to the working location.
#
# Your implementation of the five graph nodes should go in:
#
#   agent/nodes.py  (stubs with NotImplementedError are already there)
#
# Do not edit this file.
