# This file is a reference scaffold — it has been moved to the working location.
#
# Your implementation of AgentState should go in:
#
#   agent/state.py  (AgentState TypedDict is already scaffolded there)
#
# Do not edit this file.